[project]
name = "tiktokaivideogenerator"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "edge-tts>=7.0.0",
    "groq>=0.16.0",
    "moviepy==1.0.3",
    "openai==1.85.0",
    "openai-whisper>=20240930",
    "requests>=2.32.3",
]
